version: 1.0.9.{build}

init:
  - set PACKAGE_PRERELEASE_SUFFIX=

build_script:
- build-appveyor.cmd

test:
  assemblies:
    - '**\*Ditto.Resolvers.*Tests.dll'

artifacts:
  - path: build\artifacts\*.nupkg
    name: nuget

deploy:
    # GitHub Deployment for releases
  - provider: GitHub
    auth_token:
      secure: YU4cemY4TPZOCG/zDtTQJybuIaIh62eIfFMAwyTzgUmwCWeHFRGZHePwttPvwcyP
    artifact: /.*\.zip/            # upload all Zip packages to release assets
    draft: false
    prerelease: false
    on:
      branch: master
      appveyor_repo_tag: true        # deploy on tag push only

    # NuGet Deployment for releases
  - provider: NuGet
    server: 
    api_key:
      secure: fK6HViQb+42cziwzfw5OrwJG3LC6gl+NDLicTi2az4XwL6O0wqrdmDL7zmsB1787
    artifact: nuget
    on:
      branch: master
      appveyor_repo_tag: true